# Generated by Django 2.2.6 on 2019-10-14 07:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_by', models.CharField(max_length=255)),
                ('booked_for', models.CharField(max_length=255)),
                ('total_amount_paid', models.PositiveIntegerField()),
                ('is_paid', models.BooleanField()),
                ('payment_method', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LayoutItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('seat_count', models.PositiveIntegerField()),
                ('layout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiv1.Layout')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('departure_point', models.CharField(max_length=255)),
                ('layout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiv1.LayoutItem')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiv1.Route')),
                ('vechicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiv1.Vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiv1.VehicleType'),
        ),
        migrations.CreateModel(
            name='SeatItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5)),
                ('state', models.CharField(choices=[('unavailable', 'unavailable'), ('available', 'available'), ('locked', 'locked'), ('booked', 'booked')], default='available', max_length=15)),
                ('booking_details', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiv1.Booking')),
                ('layout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiv1.Layout')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5)),
                ('state', models.CharField(choices=[('unavailable', 'unavailable'), ('available', 'available'), ('locked', 'locked'), ('booked', 'booked')], default='available', max_length=15)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv1.Layout')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiv1.VehicleItem'),
        ),
    ]
