# Generated by Django 2.2.6 on 2019-10-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='seat_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
