# Generated by Django 2.2.6 on 2019-10-14 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0002_layout_seat_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicletype',
            name='seat_count',
        ),
    ]
