# Generated by Django 2.2.6 on 2019-10-14 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0003_remove_vehicletype_seat_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleitem',
            name='layout',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiv1.LayoutItem'),
        ),
    ]
