# Generated by Django 2.2.6 on 2019-10-14 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0004_auto_20191014_0750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='vehicle',
            new_name='vehicle_item',
        ),
        migrations.RemoveField(
            model_name='seatitem',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='vehicleitem',
            name='layout',
        ),
        migrations.AddField(
            model_name='seatitem',
            name='layout_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apiv1.LayoutItem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seatitem',
            name='vehicle_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apiv1.VehicleItem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicleitem',
            name='layout_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='apiv1.LayoutItem'),
        ),
    ]
