# Generated by Django 2.2.6 on 2019-10-13 07:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('departure_point', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_by', models.CharField(max_length=255)),
                ('booked_for', models.CharField(max_length=255)),
                ('total_amount_paid', models.PositiveIntegerField()),
                ('is_paid', models.BooleanField()),
                ('payment_method', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_module.ActiveVehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('seat_count', models.PositiveIntegerField()),
                ('seat_x', models.PositiveIntegerField()),
                ('seat_y', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=255)),
                ('bus_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_module.VehicleType')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('booking_details', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_module.Booking')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_module.ActiveVehicle')),
            ],
        ),
        migrations.AddField(
            model_name='activevehicle',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_module.Route'),
        ),
        migrations.AddField(
            model_name='activevehicle',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_module.Vehicle'),
        ),
    ]
