# Generated by Django 2.2.6 on 2019-10-13 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('json_string', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicletype',
            name='seat_x',
        ),
        migrations.RemoveField(
            model_name='vehicletype',
            name='seat_y',
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='layout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_module.Layout'),
        ),
    ]
