# Generated by Django 2.2.6 on 2019-10-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_module', '0002_auto_20191013_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layout',
            old_name='x',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='layout',
            old_name='json_string',
            new_name='layout',
        ),
        migrations.RenameField(
            model_name='layout',
            old_name='y',
            new_name='width',
        ),
    ]
