# Generated by Django 2.2.6 on 2019-10-13 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_module', '0003_auto_20191013_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='bus_type',
            new_name='vehicle_type',
        ),
    ]
