# Generated by Django 2.2.6 on 2019-10-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_module', '0004_auto_20191013_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layout',
            old_name='layout',
            new_name='grid',
        ),
    ]
