# Generated by Django 2.2.6 on 2019-10-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_module', '0005_auto_20191013_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='number',
            new_name='seat_number',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='is_active',
        ),
        migrations.AddField(
            model_name='seat',
            name='state',
            field=models.CharField(choices=[(0, 'unavailable'), (1, 'available'), (2, 'locked'), (3, 'booked')], default=1, max_length=15),
        ),
    ]
